### ISSUE TITLE
关于css不能使用scoped的问题

### ISSUE THREAD

**Issue by Archsx** [FrankFang/qjVPO7f89org#1]
老师说我们制作组件的时候不要使用scoped，原因是生成的不能保证data-v-xxxxxx是稳定的。我想问一下这个data-v-xxxxxx是什么时候生成的? 是我们在npm run build的时候，生成的gulu的组件的css里面就带有data-v-xxxxxx了吗？所以别人npm install我们写的组件的时候，里面的css就已经带有data-v-xxxxxx了？

**Comment by FrankFang** [comment]
在页面中挂载组件的时候生成的；
是的。
